/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GRAFICOS;
import MODELOS.Imagen;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Random;
/**
 *
 * @author CAMILO
 */
public class Tablero extends javax.swing.JPanel implements Runnable{
    private boolean jugando;
    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        this.jugando = true;
    }

    public boolean isJugando() {
        return jugando;
    }

    public void setJugando(boolean jugando) {
        this.jugando = jugando;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void run(){
        while(this.jugando==true){
 
        }
    }
    
    public int numeroAleatorio(){
        //esto genera un numero aleatorio el cual sera designado para un tipo de ficha
        Random aleatorio = new Random(System.currentTimeMillis());
        int intAletorio = aleatorio.nextInt(6);
        return intAletorio;
    }
    
    public void generarFicha(int num){
        //esto va a generar una ficha dependiendo de un numero de entre el 0 al 6 (6 incluido)
    }
    
    public void dibujarBordeArriba(Graphics g){
        Toolkit t = Toolkit.getDefaultToolkit();
        Image imagen = t.getImage("src/IMAGENES/tierra con pasto.png");
        for(int i = 0; i <= 300; i+=25){
            g.drawImage(imagen, i, 0, 25, 25, this);
        }
    }
    
    public void dibujarBordeAbajo(Graphics g){
        Toolkit t = Toolkit.getDefaultToolkit();
        Image imagen = t.getImage("src/IMAGENES/piedra.jpg");
        for(int i = 0; i <= 300; i+=25){
            g.drawImage(imagen, i, 525, 25, 25, this);
        }  
    }
    
    public void dibujarBordeLados(Graphics g){
        Toolkit t = Toolkit.getDefaultToolkit();
        Image imagen = t.getImage("src/IMAGENES/tierra.jpg");
        for(int j = 0; j <= 275; j+=275){
            for(int i =25; i <= 550; i+=25){
                g.drawImage(imagen, j, i, 25, 25, this);
            }
        }
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        dibujarBordeLados(g);
        dibujarBordeAbajo(g);
        dibujarBordeArriba(g);
    }
        
        
}
